baseURL: "https://erica-scarpa.github.io/" 
title: Erica Scarpa
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: erica_scarpa

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Courses
          url: /courses/
          weight: 2
        - name: Design
          url: /design/
          weight: 3
        - name: Tags
          url: /tags/
          weight: 5     
        - name: Newsletter
          url: https://pmichaillat.substack.com
          weight: 4

params:
    description: "I am a postdoctoral fellow at the Unversity of Turin, Sept. of Historical Studies. I work on social history, data mining and data visualization applied to cuneiform sources, historical geography, and digital humanities."
    author: Erica Scarpa
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pascal Michaillat
          subtitle: "I am a postdoctoral fellow at the Unversity of Turin, Sept. of Historical Studies. I work on social history, data mining and data visualization applied to cuneiform sources, historical geography, and digital humanities."
          imageUrl: "/prof_pic.jpg"
          imageWidth: 170
          imageHeight: 170
          imageTitle: Erica Scarpa
          buttons:
            - name: Papers
              url: /papers/
            - name: Courses
              url: /courses/
            - name: Design
              url: /design/
            - name: Newsletter
              url: https://pmichaillat.substack.com
    socialIcons:
        - name: CV
          url: assets/cv.pdf
        - name: Email
          url: mailto:erica.scarpa@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=Yd4Me1UAAAAJ&hl=it
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/erica-scarpa
        # - name: Substack
        #   url: https://pmichaillat.substack.com

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Pascal Michaillat"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
